db:
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: taco_service
    MYSQL_ROOT_PASSWORD: my-secret-pw
  ports:
    - "3306:3306"
  volumes:
    - ./data:/data

service:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/code

