db:
  image: mysql:latest
  environment:
    MYSQL_DATABASE: team_tacos
    MYSQL_ROOT_PASSWORD: my-secret-pw
    MYSQL_USER: root
    MYSQL_PASSWORD: admin123
  ports:
    - "3306:3306"
  volumes:
    - ./data:/data

service:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/code

