development:
  adapter: mysql2
  reconnect: false
  database: taco_service
  pool: 5
  username: root
  password: my-secret-pw
  host: db


test:
  adapter: mysql2
  reconnect: false
  database: taco_service
  pool: 5
  username: root
  password: my-secret-pw
  host: db
