development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-team_tacos_dev
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test-team_tacos
  pool: 5
  username: root
  password:
