development:
  adapter: mysql2
  reconnect: false
  database: <%= ENV['DB_ENV_MYSQL_DATABASE']%>
  pool: 5
  username: root
  password: <%= ENV['DB_1_ENV_MYSQL_ROOT_PASSWORD']%>
  host: <%= ENV['DB_1_PORT_3306_TCP_ADDR']%>


test:
  adapter: mysql2
  reconnect: false
  database: <%= ENV['DB_ENV_MYSQL_DATABASE']%>
  pool: 5
  username: root
  password: <%= ENV['DB_1_ENV_MYSQL_ROOT_PASSWORD']%>
  host: <%= ENV['DB_1_PORT_3306_TCP_ADDR']%>
